'use client';

type LandRow = { kode: string; luas: string; utama: string; sisipan: string; kimia: string };
type Season = { tanam: string; panen: string; produksi: string; pendataan: string };
type Boundary = { jenis: string; pemilik: string; status: string };
type Livestock = { jenis: string; jumlah: string; pakan: string; kondisi: string };
type Props = { nama: string; kode: string; alamat: string; kelompok: string; alamatLahan: string; statusMilik: string; lands: LandRow[]; totalArea: number; seasons: Season[]; boundaries: Record<string, Boundary>; livestock: Livestock[] };
const cell = 'border border-black px-2 py-1 text-[10px]';
const directions = ['Barat', 'Timur', 'Selatan', 'Utara'];
export default function DataLahanPreview(props: Props) {
  return <div className="pdf-preview flex justify-center bg-slate-100 py-6 print:bg-white print:py-0"><style>{'@media print { @page { size: A4; margin: 0; } .pdf-preview, .pdf-preview * { box-shadow: none !important; } .pdf-preview .pdf-paper, .pdf-preview .pdf-paper * { border-color: #000 !important; } }'}</style><article className="pdf-paper w-[210mm] min-h-[297mm] border-0 bg-white p-7 text-black shadow-2xl print:border-0 print:shadow-none" style={{ fontFamily: 'Arial, sans-serif' }}>
    <header className="border-b-[3px] border-double border-black pb-3 text-center"><p className="mb-1 text-lg font-black tracking-widest">APPOLI</p><p className="text-sm font-bold">Aliansi Petani Padi dan Palawija Organik Boyolali</p><p className="text-[10px]">Dk. Mencil RT.02/01 Desa Glongong, Kec. Nogosari, Kab. Boyolali</p></header><h1 className="my-4 text-center text-sm font-bold underline">FORMULIR PENDATAAN PETANI DAN LAHAN</h1>
    <table className="mb-4 w-full border-collapse"><tbody><tr><Label text="Nama Petani" /><td className={cell}>{props.nama || '-'}</td><Label text="Kode Petani" /><td className={cell}>APL / {props.kode || '-'}</td></tr><tr><Label text="Alamat Petani" /><td className={cell}>{props.alamat || '-'}</td><Label text="Kelompok Tani" /><td className={cell}>{props.kelompok || '-'}</td></tr><tr><Label text="Alamat Lahan" /><td className={cell}>{props.alamatLahan || '-'}</td><Label text="Status Kepemilikan" /><td className={cell}>{props.statusMilik || '-'}</td></tr></tbody></table>
    <Title>Lahan pertanian organik</Title><table className="mb-4 w-full border-collapse"><thead><tr className="bg-slate-800 text-white"><th className={cell}>Kode lahan</th><th className={cell}>Luas (Ha)</th><th className={cell}>Tanaman utama</th><th className={cell}>Tanaman sisipan</th><th className={cell}>Pemakaian terakhir kimia</th></tr></thead><tbody>{props.lands.map((land) => <tr key={land.kode}><td className={cell}>{land.kode}</td><td className={cell}>{land.luas || '-'}</td><td className={cell}>{land.utama || '-'}</td><td className={cell}>{land.sisipan || '-'}</td><td className={cell}>{land.kimia || '-'}</td></tr>)}<tr className="bg-sky-100 font-bold"><td className={`${cell} text-right`}>Total luas</td><td className={cell}>{props.totalArea.toLocaleString('id-ID', { maximumFractionDigits: 4 })} Ha</td><td colSpan={3} className={cell} /></tr></tbody></table>
    <Title>Kalender masa tanam dan estimasi produksi</Title><table className="mb-4 w-full border-collapse"><thead><tr className="bg-slate-800 text-white"><th className={cell}>Masa tanam</th><th className={cell}>Tanggal tanam</th><th className={cell}>Tanggal panen</th><th className={cell}>Produksi (Kg)</th><th className={cell}>Tanggal pendataan</th></tr></thead><tbody>{props.seasons.map((season, index) => <tr key={index}><td className={`${cell} font-bold`}>MT {index + 1}</td><td className={cell}>{season.tanam || '-'}</td><td className={cell}>{season.panen || '-'}</td><td className={cell}>{season.produksi || '-'}</td><td className={cell}>{season.pendataan || '-'}</td></tr>)}</tbody></table>
    <Title>Batas koordinat geografis lahan</Title><table className="mb-4 w-full border-collapse"><thead><tr className="bg-slate-800 text-white"><th className={cell}>Informasi batas</th>{directions.map((direction) => <th key={direction} className={cell}>{direction}</th>)}</tr></thead><tbody>{(['jenis', 'pemilik', 'status'] as const).map((field) => <tr key={field}><td className={`${cell} bg-slate-200 font-bold`}>{field === 'jenis' ? 'Jenis batas' : field === 'pemilik' ? 'Pemilik' : 'Status lahan'}</td>{directions.map((direction) => <td key={direction} className={cell}>{props.boundaries[direction][field] || '-'}</td>)}</tr>)}</tbody></table>
    <Title>Ternak pendukung pupuk alami</Title><table className="mb-4 w-full border-collapse"><thead><tr className="bg-slate-800 text-white"><th className={cell}>Jenis ternak</th><th className={cell}>Jumlah</th><th className={cell}>Pakan dan pengobatan</th><th className={cell}>Kondisi ternak</th></tr></thead><tbody>{props.livestock.map((animal, index) => <tr key={index}><td className={cell}>{animal.jenis || '-'}</td><td className={cell}>{animal.jumlah || '-'}</td><td className={cell}>{animal.pakan || '-'}</td><td className={cell}>{animal.kondisi || '-'}</td></tr>)}</tbody></table><div className="mt-12 grid grid-cols-2 text-center text-[10px]"><div>Petani<p className="mb-8 mt-10">(................................)</p><b>{props.nama || '-'}</b></div><div>Petugas<p className="mb-8 mt-10">(................................)</p></div></div><footer className="mt-6 border-t border-black pt-2 text-center text-[8px]">Dokumen hasil pendataan dan verifikasi kondisi aktual di lapangan.</footer>
  </article></div>;
}
function Label({ text }: { text: string }) { return <td className={`${cell} bg-slate-200 font-bold`}>{text}</td>; }
function Title({ children }: { children: React.ReactNode }) { return <h2 className="mb-2 mt-3 border-l-4 border-sky-600 bg-slate-100 px-2 py-1 text-[11px] font-bold uppercase">{children}</h2>; }
